//  Generated by entity-cli

import * as mongoose from "mongoose";


export const schemaName = 'Menu';

export interface MenuInterface extends mongoose.Document {
    nom: string;
    description: string;
    dateDebut: Date;
    dateFin: Date;
    plats: [any];
}

export const Menu = new mongoose.Schema(
    {
        nom: {
            type: String,
            require: true,
        },
        description: {
            type: String,
            require: true,
        },
        dateDebut: {
            type: Date,
            require: true,
        },
        dateFin: {
            type: Date,
            require: true,
        },

        plats: [
            {
                type: mongoose.Schema.Types.ObjectId,
                ref: "Plat",
            },
        ],
    },
    { timestamps: true },
);
